# -*- coding: utf-8 -*-
"""F1 Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_f1DfkZtzERTKNSR3LPIg2h35E2JnVoV

Have you ever been watching Formula 1 and been bored because the driver sitting on pole wins the race week after week? Have you ever been on the edge of your seat because someone who started at the back clawed their way to the front lap after lap?

Of course you have!

This analysis seeks to answer the age-old question: can final position be predicated based on starting position? This is a univariate analysis focusing on a small sample of races during Ferrari's Schumacher hay-day.
"""

#Step 1: upload the data
#I'm using Google Colab, so the CSV files goes in directly into files -> content

#import packages
import pandas as pd
import matplotlib.pyplot as mat

f1_data = pd.read_csv('F1 Data set - Starts and Stops.csv', encoding='latin1')
f1_data.head()

"""I built my own data set for this analysis using publicly available data on the F1 website: https://www.formula1.com/en/results/1950/races/94/great-britain/starting-grid.

I made two tables in Excel, one of starting grids, one of race results, since F1 does not combine these tables already. I then assigned each row a unique ID that allowed me to match up the starting position and result for each driver in each race. This analysis treats each individual driver's performance in the race as an individual data point / row.
"""

#the encoding added a character at the beginning of some strings, so let's remove that!

f1_data['Driver'] = f1_data['Driver'].str.strip('Ê')

chars_to_remove = "Ê"
translation_table = str.maketrans(dict.fromkeys(chars_to_remove))

f1_data['Race_ID'] = f1_data['Race_ID'].str.translate(translation_table)
f1_data.head()

#checking out the data set data types

datatypes = f1_data.dtypes
print(datatypes)

#dropping NA's and instances where drivers didn't complete the race.
#These instances will mess up the analysis because you cannot predict a crash or mechanical malfunction based on starting position.

indexf1 = f1_data[(f1_data['Pos'] == 'NC')].index
f1_data.drop(indexf1, inplace=True)

f1_data = f1_data.dropna()

print(f1_data)

#switching the key columns to integers so it's easier to call them later

f1_data['Pos'] = f1_data['Pos'].astype(int)
f1_data['No'] = f1_data['No'].astype(int)
f1_data['Starting_Position'] = f1_data['Starting_Position'].astype(int)

#switching Year to be a float so it isn't a continuous variable in graphs
f1_data['Year'] = f1_data['Year'].astype(float)

display(f1_data.dtypes)

"""Now that the data is relatively clean, let's get a better sense of it."""

#shape of the data

rows = f1_data.shape[0]
cols = f1_data.shape[1]

print("Rows: " + str(rows))
print("Columns: " + str(cols))

#column names

for col in f1_data.columns:
    print(col)

#This looks at how many times each individual driver appears in the data set.

f1_data['Driver'].value_counts()

""" Schumacher was in 102 races, while Enge was only in 2. Most drivers were in 50 races. Schumacher's overrepresentation in the data set is a concern, but since we are not taking driver into account, only starting position, I am not going to make any changes."""

#There were 17 different locations for races.

f1_data['Location'].value_counts()

#there were 20 participating car companies

f1_data['Car'].value_counts()

#The data covers races across three years: 2000, 2001, 2002

f1_data['Year'].value_counts()

#there are roughly the same number of races per year

years_tab = f1_data['Year'].value_counts()

mat.bar(years_tab.index, years_tab.values)
mat.title('Races per Year')
mat.xlabel('Year')
mat.ylabel('Races')
mat.show()

#subset data frame to have just winners

winners = f1_data[f1_data["Pos"] == 1]
winners.head()

#Common Winners

winners.head()

table_winners = pd.crosstab(winners['Driver'], 'no_of_times')
print(table_winners)

winners_tab = winners['Driver'].value_counts()

mat.bar(winners_tab.index, winners_tab.values)
mat.title('Number of Wins by Driver')
mat.xlabel('Driver')
mat.ylabel('Wins')
mat.show()

"""To no one's surprise, Shumacher won almost every race. In case you were wondering, he is the GOAT. At least in this analysis. Next, Hakkinen, Coulthard, and Barrichello won roughly the same number of races in the 3-year span the data set uses. Montoya finishes out the winner's circle. So, over the course of 3 years, only 5 drivers managed to win a race at all."""

#subset data frame to have just drivers who started on pole

good_start = f1_data[f1_data["Starting_Position"] == 1]
good_start.head()

#Common 1st Place Starters

first_place_starters = pd.crosstab(good_start['Driver'], 'no_of_times')
print(first_place_starters)

mat.bar(first_place_starters.index, first_place_starters['no_of_times'].values)
mat.title('First Place Starters')
mat.xlabel('Driver')
mat.ylabel('Number of Times on Pole')
mat.show()

"""Unsurprisingly, and in support of this anlysis' hypothesis, Schumacher also started on pole more often than anyone else. Also, notice that the drivers who started on pole are the same ones who won the races. One interesting note is that Montoya managed to win fewer races than the he started on pole."""

#Winning Car Companies

table_companies = pd.crosstab(winners['Car'], 'no_of_times')
print(table_companies)

"""Only 3 car companies managed to produce winning drivers. On the surface, this is not wholely surprising; better cars will make it easier to win, and better drivers will have an easier time winning. And, then, of course, the best drivers will be recruited by the best car companies or vise versa.Thus, it stands to reason that these aspects are highly intertwined."""

#Wins by Driver and Year

winners.value_counts(['Driver','Car', 'Year'])

"""It is interesting that Schumacher somehow managed to drive for both Ferrari and Williams in the same year. That's sort of wacky. Also a horribly bad oopsie by whoever at Ferrari allowed that to happen. But their loss is Williams' gain!"""

#Wins by Driver and Country

winners.value_counts(['Location', 'Driver'])

"""I was interested to see if there was a pattern to which driver won on which circut, but given Schumacher's dominance, it's hard to tell."""

#Winners Who Started in 1st

pole_winner  = winners[winners["Starting_Position"] == 1]
pole_winner.value_counts(["Starting_Position", 'Driver'])

"""This table shows instances where the drivers who started on pole also won. Conspicuously, Coulthard is missing; he won despite not starting on pole. If we remember, Schumacher started on pole 44 times, and won 31 races. But, he only won 19 of the races he started on pole (61%). Which means a certain percentage of the time, he is starting on pole and not finising first, and similarly, he is sometimes winning despite not starting in first.

Next, we can look at instances where drivers won without starting in first place. Rogue winners, if you will.
"""

#Winners Who Didn't Start in 1st

rogue_winner  = winners[winners["Starting_Position"] != 1]
rogue_winner.value_counts(['Driver', "Starting_Position"])

"""The drivers who are able to finish first despite not starting in first are *still* the usual front runners. And, based on this table, most of the time they start 2nd or 3rd in the line up. Though, there are instances, like Barrichello's start in 18th, where someone is able to climb up from a poor starting position, though these are rare."""

#rogue winners, the graph

rogue_hist = rogue_winner.value_counts(["Starting_Position"])

mat.hist(rogue_hist, bins = 20)
mat.show()

"""Next, let's take a closer look at some of the trends we've been seeing by isolating specific drivers."""

#Creationg the Schumacher & Hakkinen data sets

schumacher = f1_data[f1_data["No"] == 3]
hakkinen = f1_data[f1_data["No"] == 1]

schumacher.head()

hakkinen.head()

"""This next section takes a closer look at our lead drivers and the instances in which they won vs started in 1st, or not. We'll start with Schumacher."""

#Schumacher Starting Positions

table_schumacher = pd.crosstab(schumacher['Starting_Position'], 'no_of_times')
print(table_schumacher)

mat.bar(table_schumacher.index, table_schumacher['no_of_times'])
mat.xlabel('Starting Position')
mat.ylabel('Times')
mat.title("Schumacher's Starting Positions")
mat.show()

"""Schumacher only ever started in the top ten, and started in 1st more frequently than any other position. However, he did have some instances of starting in 6th.

Now we can look at Hakkinen.
"""

#Hakkinen Starting Positions

table_hakkinen = pd.crosstab(hakkinen['Starting_Position'], 'no_of_times')
print(table_hakkinen)

mat.bar(table_hakkinen.index, table_hakkinen['no_of_times'])
mat.xlabel('Starting Position')
mat.ylabel('Times')
mat.title("Hakkinen's Starting Positions")
mat.show()

"""Hakkinen actually started in 1st more often than Schumacher. But, as we saw, he usually doesn't finish in first despite this. And he never started out of the top 5."""

#For races Schumacher didn't win, what position did he finish in, and which did he start in

schumacher_lose = schumacher[schumacher["Pos"] != 1]
schumacher_lose.head()

"""The next logical question is: If he didn't win, where did he end up? Based on the table above, somewhere in teh top 10, so not quite so far from where he started.

We'll look at this again for Schumacher, too.
"""

table_schumacher_lose = pd.crosstab(schumacher_lose['Starting_Position'], 'no_of_times')
print(table_schumacher_lose)

mat.bar(table_schumacher_lose.index, table_schumacher_lose['no_of_times'])
mat.xlabel('Starting Position')
mat.ylabel('Times')
mat.title('Starting Positions when Schumacher Does Not Win')
mat.show()

table_schumacher_lose_2 = pd.crosstab(schumacher_lose['Pos'], 'no_of_times')
print(table_schumacher_lose_2)

mat.bar(table_schumacher_lose_2.index, table_schumacher_lose_2['no_of_times'])
mat.xlabel('Final Position')
mat.ylabel('Times')
mat.title('Final Positions Other than First for Schumacher')
mat.show()

"""When Schumacher doesn't win, he's actually most likely to start in 6th place. And he is most likely to finish in 3rd.

We can repeat the analysis for Hakkinen.
"""

hakkinen_lose = hakkinen[hakkinen["Pos"] != 1]
hakkinen_lose.head()

table_hakkinen_lose = pd.crosstab(hakkinen_lose['Starting_Position'], 'no_of_times')
print(table_hakkinen_lose)

mat.bar(table_hakkinen_lose.index, table_hakkinen_lose['no_of_times'])
mat.xlabel('Starting Position')
mat.ylabel('Times')
mat.title('Starting Positions when Hakkinen Does Not Win')
mat.show()

table_hakkinen_lose_2 = pd.crosstab(hakkinen_lose['Pos'], 'no_of_times')
print(table_hakkinen_lose_2)

mat.bar(table_hakkinen_lose_2.index, table_hakkinen_lose_2['no_of_times'])
mat.xlabel('Final Position')
mat.ylabel('Times')
mat.title('Final Positions Other than First for Hakkinen')
mat.show()

"""When Hakkinen doesn't win, he's most likely to have started in 1st, anyway. And he will usually finish 2nd.

This is in line with our analysis. Hakkinen isn't moving around a lot in the order, regardless of 1st place. Schumacher has more variation, but even then, he's staying in the top 10 a lot of the time, so only gaining or losing a few places per race.

We can see if this is an overall trend amongst the drivers.
"""

#For all drivers, what position did they finish in, and which did they start in

start_v_stop = f1_data.value_counts(["Pos", "Starting_Position"])
start_v_stop.sort_index(ascending=True)

"""With a final position of 1, the starting position is most often 1, but could also be 2, 3, 4, 5, etc. So, clearly there are some doubts that the pole-sitted will finish that way. However, it is *more likely*.

This next section repeats some of the previous analysis with Montoya.
"""

#Montoya - starts on pole, doesn't finish 1st


Montoya = f1_data[f1_data["Driver"] == "Montoya"]

#how many times did he start in each position
table_Montoya = pd.crosstab(Montoya['Starting_Position'], 'no_of_times')
print(table_Montoya)

"""Montoya usually starts in 6th, but he did start in 1st a few times. However, he didn't finish first very often."""

Montoya.head()

#when Montoya won, where did he start?

Montoya_wins = Montoya[Montoya["Pos"] == 1]
Montoya_wins.head()

"""Montoya only won 1 race, despite starting on pole 4 times. But, he did start in 1st for that race."""

#when he didn't win, where did he start?

Montoya_lose = Montoya[Montoya["Pos"] != 1]
table_Montoya_lose = pd.crosstab(Montoya_lose['Starting_Position'], 'no_of_times')
print(table_Montoya_lose)

"""Montoya most often starts in 4th, but he has a wide range of starting positions.

So we're seeing the same sort of trend. The pole sitter wins, and there isn't a whole lot of variation between starting position and final position, though Montoya does have more variation than Hakkinen.

This next portion transitions to seeing if the final position can be predicted based on starting position. From the analysis so far, results are mixed. While first place finishers are most likely to start in 1st, this isn't always the case. And, part of the reason is that the same guy is starting and finishing first every time.
"""

#correlation analysis

f1_data['Pos'] = pd.to_numeric(f1_data['Pos'], errors='coerce')
f1_data['Starting_Position'] = pd.to_numeric(f1_data['Starting_Position'], errors='coerce')

y = pd.Series(f1_data['Starting_Position'])
x = pd.Series(f1_data['Pos'])

correlation = y.corr(x)
correlation

"""The first step is to determine if starting position and final position are correlated. Spoiler alert: They are; highly correlated."""

import matplotlib.pyplot as plt
import numpy as np

x = x.dropna()
y = y.dropna()

x = x[np.isfinite(x)]
y = y[np.isfinite(y)]

common_indices = x.index.intersection(y.index)

x = x.reindex(common_indices)
y = y.reindex(common_indices)


plt.scatter(x, y)

plt.plot(np.unique(x), np.poly1d(np.polyfit(x, y, 1))
         (np.unique(x)), color='red')

"""That's a pretty convincing positive correlation, yeah?"""

corr_matrix = f1_data.corr(numeric_only=True)

import seaborn as sns

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

"""However, while starting position and final position are highly correlated, they're not the only thing that is correlated. Final position is also highly correlated with driver (No), and negatively correlated with points (Pts). This isn't unexpected. Schumacher wins everything, so any first place instance is highly likely to be associated with Schumacher.

Next, we can try to model the relationship between starting and final place. First, I will try a Poisson regression. This is an odd choice for this situation, but since Poisson regressions can't be negative, it isn't the worst choice. It will also yield some coefficients, which could be interesting to look at.
"""

#Poisson Regression

import statsmodels.api as sm
import numpy as np
from sklearn.model_selection import train_test_split

# training and test set
train, test = train_test_split(f1_data, test_size=0.2)

# Define dependent variable
y_train = train['Pos']
y_test = test['Pos']

# Define independent variables
X_train = train[['Starting_Position']]
X_test = test[['Starting_Position']]

# Add intercept term
X_train = sm.add_constant(X_train)
X_test = sm.add_constant(X_test)

# --- The change starts here ---
# Concatenate X and y for train and test sets
train_data = pd.concat([X_train, y_train], axis=1)
test_data = pd.concat([X_test, y_test], axis=1)

# Drop rows with missing values from the combined datasets
train_data = train_data.dropna()
test_data = test_data.dropna()

# Separate X and y after dropping missing values
X_train = train_data[['const', 'Starting_Position']]  # Include 'const'
y_train = train_data['Pos']
X_test = test_data[['const', 'Starting_Position']]  # Include 'const'
y_test = test_data['Pos']


# Ensure dependent variable is non-negative and an integer
y_train = y_train.astype(int) # Convert to integer if not already.
y_train = np.where(y_train < 1, 1, y_train) # If y < 1, make it 1 to avoid 0s
y_test = y_test.astype(int) # Convert to integer if not already.
y_test = np.where(y_test < 1, 1, y_test) # If y < 1, make it 1 to avoid 0s



# Fit Poisson regression model
poisson_model = sm.GLM(y_train, X_train, family=sm.families.Poisson()).fit()

# Display model summary
print(poisson_model.summary())

#https://github.com/KenDaupsey/Basic-Poisson-Regression-Using-Python/blob/main/Basic_Poisson_Regression.ipynb

"""From the coefficients, starting position is roughly equal to final position. However, the model isn't significant at all. This is probably because of all the correlations between variables; the assumptions of a Poisson regression aren't being met. Poisson regression requires independence of variables. We can test this more thorougly using the variance."""

# Commented out IPython magic to ensure Python compatibility.
#poisson assumptions - expected vs observed counts
#The mean and variance of the model are equal

# Importing Statistics module
import statistics

# Creating a sample of data
# Use the numerical y_train from the Poisson regression section (which was the 'Pos' column)
# Ensure it is treated as a single-dimensional array or list for statistics functions
sample_data = f1_data['Pos'].dropna()  # Drop missing values
sample_data = sample_data.astype(int)  # Convert to integer
sample_data = np.where(sample_data < 1, 1, sample_data)

print("Variance of sample set is % s"
#       %(statistics.variance(sample_data)))

# Also check the mean
print("Mean of sample set is %s"
#       %(np.mean(sample_data)))

"""After testing the assumptions, Poisson cannot be used as a model. Besides independent variables, the variance and mean must also be equal, and here, it is clear they are not.

But, that is OK! We can try other models, mainly categorical models. The first will be K Nearest Neighbors.
"""

# K Nearest Neighbors

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Reshape X to be a 2D array
X = f1_data[['Starting_Position']]  # Use double brackets to select as DataFrame
y = f1_data[['Pos']]

X = X.dropna() #Drop rows with missing values from X
y = y.dropna() #Drop rows with missing values from y

common_indices = X.index.intersection(y.index)
X = X.loc[common_indices]
y = y.loc[common_indices]

X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=1)

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

print(knn.predict(X_test))

#need to get some sort of accuracy, something to compare it to?
#https://www.geeksforgeeks.org/k-nearest-neighbor-algorithm-in-python/ <- in here, scroll down

#KNN Accuracy
print(knn.score(X_test, y_test))

"""The accuracy is bad."""

neighbors = np.arange(1, 9)
train_accuracy = np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

# Loop over K values
for i, k in enumerate(neighbors):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    # Compute training and test data accuracy
    train_accuracy[i] = knn.score(X_train, y_train)
    test_accuracy[i] = knn.score(X_test, y_test)

# Generate plot
plt.plot(neighbors, test_accuracy, label = 'Testing dataset Accuracy')
plt.plot(neighbors, train_accuracy, label = 'Training dataset Accuracy')

plt.legend()
plt.xlabel('n_neighbors')
plt.ylabel('Accuracy')
plt.show()

"""We can try to retrain the model to see if we get better results using n=6."""

#retrain the model

knn_final = KNeighborsClassifier(n_neighbors=6)
knn_final.fit(X_train, y_train)

#predict!

pred_6 = knn_final.predict([[6]])
pred_20 = knn_final.predict([[20]])
pred_1 = knn_final.predict([[1]])

print(pred_6)
print(pred_20)
print(pred_1)

#lol whoops - > it predicts people getting SUPER HIGH places.

"""K Nearest Neighbors is a better choice of model because it is categorical. However, this model is not any more accurate than the Poisson regression.

When asked to predict, the model did predict that the 1st place starter would finish in 1st, but predicted improvements for starts in 6th and 20th. This isn't really in support of the hypothesis.
"""

#naive bayes

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Initialize the Gaussian Naive Bayes classifier
gnb = GaussianNB()

# Train the model
gnb.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = gnb.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

#https://www.geeksforgeeks.org/ml-naive-bayes-scratch-implementation-using-python/
#https://machinelearningmastery.com/naive-bayes-classifier-scratch-python/
#https://www.geeksforgeeks.org/gaussian-naive-bayes-using-sklearn/

"""Lastly, a Naive Bayes model. Again, this is a categorical model, and again, it isn't very accurate.

Now, we're going to switch gears (pun intended). Up until now, we've been trying to predict the ending position, but there's too many factors. The original hypothesis was that drivers couldn't change by too many positions. So! Let's see if we can remove the actual position number and see some improvements.
"""

#making a new column in the original data
#this one calculates the change in places - it's backwards so it's negative if you move away from 1st,
#and positive if you move towards 1st

f1_data['delta_place'] = f1_data['Pos'] - f1_data['Starting_Position']
f1_data['delta_place'] = f1_data['delta_place'] * -1
f1_data.head()

mat.hist(f1_data['delta_place'])
mat.title('Changes in Place from Start to Finish')
mat.xlabel('Places Gained(-) or Lost(+)')
mat.ylabel('Count')
mat.show()

"""Most times, people lose 1-5 places (remember, negative is good). But, a lot will gain 1 or 2 places. It's very rare to either fall to the back of the grid, but it's rarer to claw your way back up once you're there."""

#added another column - this one is categorical
#lost is bad, gained is good, stayed the same is self explanatory

f1_data['place_status'] = f1_data['delta_place'].apply(lambda x: "lost places" if x > 0 else ("gained places" if x < 0 else "stayed in place"))
f1_data.head()

"""We can try to vizualize this.

Lost places = 0 (lightest purple)
Gained places = 1 (medium purple)
Stayed in Place = 2 (darkest purple)
"""

import seaborn as sns

f1_data['kde_hue'] = f1_data['place_status']
f1_data['kde_hue'].replace(['lost places', 'gained places', 'stayed in place'],
                        [0, 1, 2], inplace=True)


sns.kdeplot(data=f1_data, x="Starting_Position", hue="kde_hue", fill = True)

"""You can lose places from anywhere. It's really common to lose a place. But it's harder to stay in place or gain a place unless you're at the front. Staying in place is less frequent, but happens no matter where you are. If you're already at the front, there's a higher density of instances where front runners will gain places. This is consistent with what we've seen. It's impossible to claw your way up to 1st from the back, but if you start in 2nd, it's not unlikely you'll be able to swap into 1st.

Now we see if we can use our new columns for prediction!
"""

#redoing the matrix to see if the new columns correlate to anything

corr_matrix = f1_data.corr(numeric_only=True)

# Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

"""delta_place is correlated with starting position, and somewhat with driver.

The moment of truth: modeling!
Here I'm using Baysian analysis with the number of places lost or gained. KNN would also work with this analysis, but Baysian is a simpler model.
"""

#bringing back Naive Bayes
#delta place

# Reshape X to be a 2D array
X = f1_data[['Starting_Position']]  # Use double brackets to select as DataFrame
y = f1_data[['delta_place']]

common_indices = X.index.intersection(y.index)
X = X.loc[common_indices]
y = y.loc[common_indices]

X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=1)

gnb.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = gnb.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

"""It's still extremely inaccurate :/ so that's depressing. It's really hard to predict how many places someone will change based just on where they started.

Let's try again. This time, we'll use not the number of places lost or gained, but the classification: did they lose, gain, or stay the same.
"""

# prediciting place status

X = f1_data[['Starting_Position']]  # Use double brackets to select as DataFrame
y = f1_data[['place_status']]

common_indices = X.index.intersection(y.index)
X = X.loc[common_indices]
y = y.loc[common_indices]

X_train, X_test, y_train, y_test = train_test_split(
             X, y, test_size = 0.2, random_state=1)

gnb.fit(X_train, y_train)

# Predict the labels for the test set
y_pred = gnb.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')

"""It worked! Based purely on starting position, it IS possible to predict if places will be lost or gained based on starting possition alone, but it is not possible to predict what place someone will finish or how many places will be lost or gained.

Let's see that accuracy in action!
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')

"""The modle is really good at prediciting if someone will gain a place, but it's maybe not very good at predicting if someone will stay in the same place, or if they will lose a place.

In conclusion: it is not possible to predict final position based soley on starting position despite the majority of 1st place finishers having also started in 1st. But, it may be possible to predict if someone will lose or gain places (or not).

It is possible that the models just needed more data. The data set here is small, spanning only 3 years, specifically 3 years where the same drive kept winning. If more data from more years was added, it may be that a stronger pattern is seen.
"""